// Code generated by MockGen. DO NOT EDIT.
// Source: coin_history.go

// Package repository is a generated GoMock package.
package repository

import (
	conf "price_api/price_server/config"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCoinHistoryRepository is a mock of CoinHistoryRepository interface.
type MockCoinHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoinHistoryRepositoryMockRecorder
}

// MockCoinHistoryRepositoryMockRecorder is the mock recorder for MockCoinHistoryRepository.
type MockCoinHistoryRepositoryMockRecorder struct {
	mock *MockCoinHistoryRepository
}

// NewMockCoinHistoryRepository creates a new mock instance.
func NewMockCoinHistoryRepository(ctrl *gomock.Controller) *MockCoinHistoryRepository {
	mock := &MockCoinHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockCoinHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinHistoryRepository) EXPECT() *MockCoinHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetHistoryBySymbol mocks base method.
func (m *MockCoinHistoryRepository) GetHistoryBySymbol(idx, pageSize int, symbol string) ([]conf.PriceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryBySymbol", idx, pageSize, symbol)
	ret0, _ := ret[0].([]conf.PriceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryBySymbol indicates an expected call of GetHistoryBySymbol.
func (mr *MockCoinHistoryRepositoryMockRecorder) GetHistoryBySymbol(idx, pageSize, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryBySymbol", reflect.TypeOf((*MockCoinHistoryRepository)(nil).GetHistoryBySymbol), idx, pageSize, symbol)
}

// GetHistoryBySymbolAndTimestamp mocks base method.
func (m *MockCoinHistoryRepository) GetHistoryBySymbolAndTimestamp(symbol string, timestamp int64) ([]conf.PriceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryBySymbolAndTimestamp", symbol, timestamp)
	ret0, _ := ret[0].([]conf.PriceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryBySymbolAndTimestamp indicates an expected call of GetHistoryBySymbolAndTimestamp.
func (mr *MockCoinHistoryRepositoryMockRecorder) GetHistoryBySymbolAndTimestamp(symbol, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryBySymbolAndTimestamp", reflect.TypeOf((*MockCoinHistoryRepository)(nil).GetHistoryBySymbolAndTimestamp), symbol, timestamp)
}

// GetHistoryByTimestamp mocks base method.
func (m *MockCoinHistoryRepository) GetHistoryByTimestamp(timestamp int64) ([]conf.PriceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryByTimestamp", timestamp)
	ret0, _ := ret[0].([]conf.PriceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryByTimestamp indicates an expected call of GetHistoryByTimestamp.
func (mr *MockCoinHistoryRepositoryMockRecorder) GetHistoryByTimestamp(timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryByTimestamp", reflect.TypeOf((*MockCoinHistoryRepository)(nil).GetHistoryByTimestamp), timestamp)
}

// GetTotalHistoryBySymbol mocks base method.
func (m *MockCoinHistoryRepository) GetTotalHistoryBySymbol(symbol string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalHistoryBySymbol", symbol)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalHistoryBySymbol indicates an expected call of GetTotalHistoryBySymbol.
func (mr *MockCoinHistoryRepositoryMockRecorder) GetTotalHistoryBySymbol(symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalHistoryBySymbol", reflect.TypeOf((*MockCoinHistoryRepository)(nil).GetTotalHistoryBySymbol), symbol)
}

// InsertPriceInfo mocks base method.
func (m *MockCoinHistoryRepository) InsertPriceInfo(cfg conf.PriceInfos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPriceInfo", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPriceInfo indicates an expected call of InsertPriceInfo.
func (mr *MockCoinHistoryRepositoryMockRecorder) InsertPriceInfo(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPriceInfo", reflect.TypeOf((*MockCoinHistoryRepository)(nil).InsertPriceInfo), cfg)
}
