// Code generated by MockGen. DO NOT EDIT.
// Source: update_price_history.go

// Package repository is a generated GoMock package.
package repository

import (
	vo "price_api/price_server/internal/vo"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUpdatePriceRepository is a mock of UpdatePriceRepository interface.
type MockUpdatePriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatePriceRepositoryMockRecorder
}

// MockUpdatePriceRepositoryMockRecorder is the mock recorder for MockUpdatePriceRepository.
type MockUpdatePriceRepositoryMockRecorder struct {
	mock *MockUpdatePriceRepository
}

// NewMockUpdatePriceRepository creates a new mock instance.
func NewMockUpdatePriceRepository(ctrl *gomock.Controller) *MockUpdatePriceRepository {
	mock := &MockUpdatePriceRepository{ctrl: ctrl}
	mock.recorder = &MockUpdatePriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatePriceRepository) EXPECT() *MockUpdatePriceRepositoryMockRecorder {
	return m.recorder
}

// GetTotalUpdatePriceHistoryBySymbol mocks base method.
func (m *MockUpdatePriceRepository) GetTotalUpdatePriceHistoryBySymbol(symbol string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUpdatePriceHistoryBySymbol", symbol)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUpdatePriceHistoryBySymbol indicates an expected call of GetTotalUpdatePriceHistoryBySymbol.
func (mr *MockUpdatePriceRepositoryMockRecorder) GetTotalUpdatePriceHistoryBySymbol(symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUpdatePriceHistoryBySymbol", reflect.TypeOf((*MockUpdatePriceRepository)(nil).GetTotalUpdatePriceHistoryBySymbol), symbol)
}

// GetUpdatePriceHistoryBySymbol mocks base method.
func (m *MockUpdatePriceRepository) GetUpdatePriceHistoryBySymbol(idx, pageSize int, symbol string) ([]vo.UpdatePirceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatePriceHistoryBySymbol", idx, pageSize, symbol)
	ret0, _ := ret[0].([]vo.UpdatePirceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatePriceHistoryBySymbol indicates an expected call of GetUpdatePriceHistoryBySymbol.
func (mr *MockUpdatePriceRepositoryMockRecorder) GetUpdatePriceHistoryBySymbol(idx, pageSize, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatePriceHistoryBySymbol", reflect.TypeOf((*MockUpdatePriceRepository)(nil).GetUpdatePriceHistoryBySymbol), idx, pageSize, symbol)
}
